name: CI/CD Pipeline

on:
  push:
    branches:
      - main # or whatever your main branch is

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or your current version

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd Job-Application-Tracker
            git pull
            chmod +x deploy.sh
            ./deploy.sh
